Feature/relation/daolove0323
kakao-tech-campus-2nd-step3/Team26_BE pull request #46
Opened 2024-10-16 11:30 UTC by Daolove0323

## 🔥 Pull requests

🌳 **작업 브랜치**

- Feature/relation/daolove0323

⚒ **작업 내용**

- common 리팩토링
- event, image, reservation 연관관계 설정
- image 도메인 리팩토링

## ⚠ 참고 사항

- image 도메인 추후 피드백 후 수정예정

## 📸 스크린샷(선택)

|기능 | 스크린샷 |
| :-: | :------: |
|  |  |

2024-10-16 11:54 UTC, ariimo approved these changes

2024-10-16 12:03 UTC, lja3723 requested changes

2024-10-16 12:03 UTC, lja3723 commented on src/main/java/org/ktc2/cokaen/wouldyouin/member/persist/Curator.java
> -    @OneToMany(mappedBy = "curator")
이거 왜 바꾸셨나요? revert 까먹었죠?

2024-10-16 12:03 UTC, lja3723 commented on src/main/resources/application.properties
> +image.upload.common-path=src/main/resources/static
이거 제거했는데 왜 추가하셨죠? pull 확인 제대로 안하셨죠?

2024-10-16 12:06 UTC, Daolove0323 commented on src/main/java/org/ktc2/cokaen/wouldyouin/Image/api/GetImageService.java
> +public class GetImageService {
아직 사용되는 부분이 없는 코드라,, 피드백 이후 수정하겠습니다

2024-10-16 12:07 UTC, Daolove0323 commented on src/main/java/org/ktc2/cokaen/wouldyouin/member/persist/Curator.java
> -    @OneToMany(mappedBy = "curator")
그래도 실행되는 상태로 보내느게 나을거같아서요!

2024-10-16 12:09 UTC, lja3723 commented on src/main/java/org/ktc2/cokaen/wouldyouin/member/persist/Curator.java
> -    @OneToMany(mappedBy = "curator")
그럼 host도 hostId로 바꾸지 그랬어요

2024-10-16 12:10 UTC, Daolove0323 commented on src/main/resources/application.properties
> +image.upload.common-path=src/main/resources/static
확인은 했는데,, 갑자기 삭제되고 yml 파일이 4개 생겨서 일단 넣어뒀어요ㅜ

2024-10-16 12:11 UTC, Daolove0323 commented on src/main/java/org/ktc2/cokaen/wouldyouin/member/persist/Curator.java
> -    @OneToMany(mappedBy = "curator")
host는 제가 event 연관관계 추가하면서 제대로 동작합니다!

2024-10-17 10:10 UTC, lja3723 requested changes

2024-10-17 10:10 UTC, lja3723 commented on src/main/java/org/ktc2/cokaen/wouldyouin/payment/application/PaymentService.java
> +    }
Map보다 Request전용 Dto를 만드시는게 좋겠습니다
`.body(BodyInserters.fromValue(request))` 로 body에 dto를 전달할 수 있습니다.

2024-10-17 10:10 UTC, lja3723 commented on src/main/java/org/ktc2/cokaen/wouldyouin/payment/dto/KakaoPayResponse.java
> +}
코드상에서는 카멜케이스를 사용해 주세요.
`@JsonNaming(SnakeCaseStrategy.class)` 를 이용해 직렬화/역직렬화 시 스네이크 케이스로 일괄 변경 부탁드립니다.

2024-10-17 10:10 UTC, lja3723 commented on src/main/resources/application.yml
> +    "secret_key": ${KAKAOPAY_SECRET_KEY}
`WOULD_YOU_IN_XXX` 로 통일하면 어떨까요?

전 카카오 클라이언트 시크릿을  WOULD_YOU_IN_KAKAO_CLIENT_SECRET 이라고 명명했습니다

2024-10-17 10:10 UTC, lja3723 commented on src/main/resources/application.yml
> +    "kakao_pay_request_host": "open-api.kakaopay.com"
제가 소셜로그인 위해 추가한 yml이 다음과 같은데, 이렇게 통일하면 어떨까요?

```yml
# for social login
oauth:
  kakao:
    uri:
      login:
        host: kauth.kakao.com
        path: /oauth/token
      access:
        host: kapi.kakao.com
        path: /v2/user/me
    client:
      id: ${WOULD_YOU_IN_KAKAO_CLIENT_ID}
      secret: ${WOULD_YOU_IN_KAKAO_CLIENT_SECRET}
    redirect_uri: ${WOULD_YOU_IN_KAKAO_REDIRECT_URI}
  google:
    uri:
      login:
        host: oauth2.googleapis.com
        path: /token
      access:
        host: www.googleapis.com
        path: /userinfo/v2/me
    client:
      id: ${WOULD_YOU_IN_GOOGLE_CLIENT_ID}
      secret: ${WOULD_YOU_IN_GOOGLE_CLIENT_SECRET}
    redirect_uri: ${WOULD_YOU_IN_GOOGLE_REDIRECT_URI}
    scope:
      - email
      - profile
```

2024-10-17 10:16 UTC, Daolove0323 commented on src/main/java/org/ktc2/cokaen/wouldyouin/payment/dto/KakaoPayResponse.java
> +}
api 문서에서 적힌걸 하나씩 복붙하다보니.. 허허 수정했습니다

2024-10-17 10:17 UTC, Daolove0323 commented on src/main/resources/application.yml
> +    "secret_key": ${KAKAOPAY_SECRET_KEY}
넹

2024-10-17 10:18 UTC, Daolove0323 commented on src/main/resources/application.yml
> +    "kakao_pay_request_host": "open-api.kakaopay.com"
결제 관련된 부분은 제약되는 부분이 많아, 저장할정보가 많이 없어요.
지금처럼 저장하는것도 괜찮지않을까요

2024-10-17 10:25 UTC, lja3723 commented on src/main/resources/application.yml
> +    "secret_key": ${KAKAOPAY_SECRET_KEY}
시스템 환경변수에 등록될 이름인데 앞에 프로젝트명이 들어갔으면 좋겠어요. 중복될 수도 있으니까요

2024-10-17 10:26 UTC, Daolove0323 commented on src/main/resources/application.yml
> +    "secret_key": ${KAKAOPAY_SECRET_KEY}
인텔리제이에서 환경변수 등록한건 저희 프로젝트에서만 사용되지 않나요??

2024-10-17 10:34 UTC, lja3723 commented on src/main/resources/application.yml
> +    "secret_key": ${KAKAOPAY_SECRET_KEY}
배포시에는 리눅스 시스템 상 환경변수에 등록해서 사용하는거라, 운영체제 수준으로 전역적인 이름이 됩니다.

2024-10-17 10:38 UTC, Daolove0323 commented on src/main/resources/application.yml
> +    "secret_key": ${KAKAOPAY_SECRET_KEY}
개발단계에서는 여러개를 개발해서 충돌 날 수 있지만,, 배포환경에선 하나만 돌리지않을까요

2024-10-17 10:39 UTC, Daolove0323 commented on src/main/java/org/ktc2/cokaen/wouldyouin/payment/application/PaymentService.java
> +    }
request Dto 있어요

2024-10-17 10:43 UTC, Daolove0323 commented on src/main/resources/application.yml
> +    "kakao_pay_request_host": "open-api.kakaopay.com"
결제관련 부분은 oauth보다는 api에 가까운것같아요. authorization을 하지 않으니까요

2024-10-17 11:02 UTC, lja3723 commented
다음 PR에 변경사항 반영 부탁드립니다

2024-10-17 11:05 UTC, lja3723 approved these changes

2024-10-17 11:06 UTC, merged